package:
  name: utility
  version: "1.0"

source:
  git_rev: v1.0
  git_url: https://github.com/JLessinger/py_utility

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - utility

about:
  home: https://github.com/JLessinger/py_utility
  license: GPL v3.0
  license_file: LICENSE
