package:
  name: utility
  version: "1.1"

source:
  url: https://github.com/JLessinger/py_utility/archive/v1.1.tar.gz
  md5: 4b87d38e93e62df5fc5d326955616cee
  sha1: 222461c11d84b0776916c391e6400953ed6bf35a
  sha256: 8bbeb238e2353ea19abad9a72a690e58ed3a60085c6607edaf956cf8ede2f960

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/JLessinger/py_utility
  license: GPL v3.0
